name: PyPi

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  test:
    runs-on: ubuntu-latest
    push:
      branches:
        - '*'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install
        run: pip3 install --quiet --upgrade setuptools wheel twine
      - name: Test
        run: python3 -m pytest tests/
        
  publish_pypi:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install
      run: pip3 install --quiet --upgrade setuptools wheel twine pytest
    - name: Test
      run: python3 -m pytest tests/
    - name: Build
      run: python3 setup.py sdist bdist_wheel
    - name: Publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: twine upload dist/*
