name: Test

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install
        run: |
          pip3 install --quiet --upgrade setuptools pytest
          pip3 install -e .
      - name: Test
        run: python3 -m pytest tests/ 